trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:
  - task: PowerShell@2
    displayName: Install_Run_SAST
    inputs:
      targetType: 'inline'
      script: |
        #docker ps
        #docker pull registry.fortidevsec.forticloud.com/fdevsec_sast:latest
        #docker images
        #docker run hello-world
        docker run --rm --mount type=bind,source=$(Build.SourcesDirectory),target=/scan registry.fortidevsec.forticloud.com/fdevsec_sast:latest sh
        ls -ltr
