trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:
  - task: PowerShell@2
    displayName: Install_Run_SAST
    inputs:
      targetType: 'inline'
      script: |
        docker ps
        docker images
        #docker run --pull always --rm --env-file /tmp/env --mount type=bind,source="$(pwd)",target=/scan registry.fortidevsec.forticloud.com/fdevsec_sast:latest
