trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:
  - task: PowerShell@2
    displayName: Install_Run_SAST
    inputs:
      targetType: 'inline'
      script: |
        # Create a temporary file for environment variables
        #$envFile = "C:\temp\env.txt"
        #New-Item -ItemType Directory -Path C:\temp -Force
        #Get-ChildItem Env:AZURE_HTTP_USER_AGENT,Env:BUILD_BUILDID | ForEach-Object { "$($_.Key)=$($_.Value)" } | Out-File -FilePath $envFile

        # Pull the Docker image
        docker pull registry.fortidevsec.forticloud.com/fdevsec_sast:latest

        # Run the Docker container
        docker run --rm --mount type=bind,source="$(Get-Location)",target=/scan registry.fortidevsec.forticloud.com/fdevsec_sast:latest
